services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-url-shortener
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shorteneradmin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=shortener

volumes:
  mongodb_data:
    driver: local